import type { Metadata } from "next";
import "./globals.css";

import localFont from "next/font/local";

// Font files can be colocated inside of `app`
const gothic = localFont({
  src: "../assets/fonts/CenturyGothic.woff2",
  display: "swap",
  variable: "--font-gothic",
});

export const metadata: Metadata = {
  title: "Win app ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gothic.variable} antialiased font-gothic`}>
        {children}
      </body>
    </html>
  );
}
